dict_of_parts = {
    "dc-motor-12-VDC-45W": "type 2, 2 x right + 2 x left",
    "SLA-Battery": "12 V, 7.2 Ah",
    "li-ion-battery": "3 x 26650, 5000 mAh 5C, 3.7 V/4.2V",
    "wheel": "4 x ",
    "dc-switch": "12V DC 10 A",
    "dc-power-plug": "",
    "connector": "4 pairs",
    "power-adapter": "12V DC, 1 A",
    "li-ion-charger": "",
    "DC-gearboxed-motor-12V-120RPM": "4 x, replacement gearboxes",
    "heavy-duty-pipe-clamp": "4 x 350+ mm",
    "ethernet-cable": "one per computer, if more than one computer",
    "5v-unmanaged-10-100-switch": "if more than two computers",
}
