dict_of_parts = {
    "rpi3bp": "",
    "dc-motor-12-VDC-45W": "type 2, 2 x right + 2 x left",
    "SLA-Battery": "",
    "XL4015": "",
    "BTS7960": "rear drive (2 motors) & steering drive (1 motor)",
    "470-mF": "",
    "Polyfuse": "optional",
    "TVS-diode": "",
    "resistor": "7 x 330-470 Ω + 4 x 1 kΩ + 4 x 2 kΩ",
    "LED": "green + red + yellow",
    "rpi-camera": "",
    "PCB-single-14x9_5": "2 x",
    "PCB-double-9x7": "",
    "pushbutton": "",
    "wheel": "4 x ",
    "ultrasonic-sensor": "4 x",
    "resistor": "",
    "LED": "4 x blue",
}
