FROM ros:jazzy

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-lc"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    git \
    python3 \
    python3-venv \
    python3-pip \
    build-essential \
    sudo \
    && rm -rf /var/lib/apt/lists/*


CMD ["bash"]
