services:
  ros:
    build: .
    container_name: bluer_ugv_ros_rpi
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/pi/git:/root/git

      # Optional: persist venv & pip cache across rebuilds (faster)
      - bluer_venv:/root/venv
      - bluer_pip_cache:/root/.cache/pip
