services:
  ros:
    build: .
    container_name: bluer_ugv_ros_rpi
    network_mode: host
    privileged: true

    user: "0:0"
    group_add:
      - "986"

    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip10:/dev/gpiochip10
      - /dev/gpiochip11:/dev/gpiochip11
      - /dev/gpiochip12:/dev/gpiochip12
      - /dev/gpiochip13:/dev/gpiochip13

      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem

    stdin_open: true
    tty: true
    volumes:
      - /home/pi/git:/root/git
      - ${HOME}/storage/:/root/storage
      - bluer_venv:/root/venv
      - bluer_pip_cache:/root/.cache/pip
      - /proc/device-tree:/proc/device-tree:ro
      - /sys/firmware/devicetree/base:/sys/firmware/devicetree/base:ro

volumes:
  bluer_venv:
  bluer_pip_cache:
