services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluer_ugv_ros_mac
    stdin_open: true
    tty: true
    init: true

    environment:
      - DEBIAN_FRONTEND=noninteractive
      - ROS_DOMAIN_ID=0
      - GZ_PARTITION=arzhang4

    volumes:
      - ${HOME}/git:/root/git:cached
      - ${HOME}/storage/:/root/storage
      - bluer_venv:/root/venv
      - bluer_pip_cache:/root/.cache/pip
      - /dev:/dev
    privileged: true
    network_mode: host

volumes:
  bluer_venv:
  bluer_pip_cache:
